version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: compliance_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    networks:
      - mlops_network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_BACKEND_STORE_URI: mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
      MLFLOW_ARTIFACT_ROOT: /mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mlops_network

  app:
    build: .
    container_name: compliance_api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_started
    networks:
      - mlops_network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - mlops_network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    networks:
      - mlops_network

volumes:
  db_data:
  mlflow_artifacts:
  prometheus_data:
  grafana_data:

networks:
  mlops_network:
    driver: bridge